---
- hosts: otaku
  become: yes
  tasks:
  - name: Install default packages | apt
    apt:
      state: latest
      pkg: "{{ item }}"
    with_items:
    - mosh
    - ruby
    - ruby-dev
    - git
  - name: Install gems
    gem: name={{ item }} state=latest user_install=no
    with_items:
      - json
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
    - jnv.unattended-upgrades
    - kamaln7.swapfile
